import "../../globals.css";
import { useEffect, useState } from "react";
import { AppPropsWithLayout } from "@/types";
import { Toaster } from "@/components/ui/sonner";
// import "@rainbow-me/rainbowkit/styles.css";
import MainLayout from "@/components/layouts/Main.layout";

import Web3ModalProvider from "@/context";
import { Props } from "@/types";
import type { Metadata } from "next";
import { headers } from "next/headers";
// import { cookieToInitialState } from "wagmi";
// import { config } from "@/config";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page);
  // For load rainbowkit, ... only front
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  return (
    <>
    <ToastContainer />
      {mounted && (
        <Web3ModalProvider>
          <MainLayout>
            <div>
              {getLayout(<Component {...pageProps} />)}
              <Toaster />
            </div>
          </MainLayout>
        </Web3ModalProvider>
      )}
    </>
  );
}
